"""Add greeting_message to agents

Revision ID: c2f62fc6c983
Revises: 002_add_prebuilt_agent_fields
Create Date: 2026-01-06 16:22:19.347364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2f62fc6c983'
down_revision: Union[str, None] = '002_add_prebuilt_agent_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('greeting_message', sa.String(), nullable=True))
    op.drop_constraint('agents_user_id_fkey', 'agents', type_='foreignkey')
    op.create_foreign_key(None, 'agents', 'users', ['user_id'], ['id'])
    op.drop_constraint('conversations_user_id_fkey', 'conversations', type_='foreignkey')
    op.drop_constraint('conversations_agent_id_fkey', 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'agents', ['agent_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'])
    op.drop_constraint('messages_conversation_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_conversation_id_fkey', 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key('conversations_agent_id_fkey', 'conversations', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('conversations_user_id_fkey', 'conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.create_foreign_key('agents_user_id_fkey', 'agents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('agents', 'greeting_message')
    # ### end Alembic commands ###

