import { defineStore } from 'pinia'
import { ref, computed, watch } from 'vue'

export type TutorStep = 
  | 'child-details'
  | 'subject-selection'
  | 'skill-assessment'
  | 'focus-areas'
  | 'topic-menu'
  | 'learning'

export type Subject = string // Now dynamic - any subject entered by user

export interface ChildDetails {
  name: string
}

export interface SkillAssessment {
  proficiency: 'beginner' | 'intermediate' | 'advanced' | null
  subject: Subject | null
}

export interface FocusArea {
  id: string
  name: string
  selected: boolean
}

export interface Topic {
  id: string
  name: string
  icon: string
}

export interface Level {
  id: string
  number: number
  name: string
  difficulty: 'easy' | 'medium' | 'hard'
}

export interface Game {
  id: string
  name: string
  type: 'quiz' | 'practice' | 'challenge'
  questions: any[]
}

export interface QuizResult {
  correct: number
  total: number
  percentage: number
  weakAreas: string[]
}

export const useTutorStore = defineStore('tutor', () => {
  const currentStep = ref<TutorStep>('child-details')
  const childDetails = ref<ChildDetails>({ name: '' })
  const selectedSubject = ref<Subject | null>(null)
  const skillAssessment = ref<SkillAssessment>({ proficiency: null, subject: null })
  // Focus areas are now optional - can be AI-generated or skipped
  // For now, return empty array since subjects are dynamic
  function getFocusAreasForSubject(subject: Subject | null): FocusArea[] {
    // Focus areas can be AI-generated later if needed
    // For now, we'll skip this step or make it optional
    return []
  }

  const focusAreas = ref<FocusArea[]>([])

  // Watch for subject changes and update focus areas
  watch(selectedSubject, (newSubject) => {
    if (newSubject) {
      focusAreas.value = getFocusAreasForSubject(newSubject)
    } else {
      focusAreas.value = []
    }
  }, { immediate: true })
  const selectedTopic = ref<Topic | null>(null)
  const currentLevel = ref<Level | null>(null)
  const currentGame = ref<Game | null>(null)
  const currentQuiz = ref<any>(null)
  const quizResults = ref<QuizResult | null>(null)
  const conversationId = ref<string | null>(null)
  const levelProgress = ref<Record<string, number>>({}) // topicId -> current level number
  const wrongAnswers = ref<Record<number, number>>({}) // question index -> count of wrong attempts

  // Topics are now dynamically generated by AI - no hard-coding
  const topics = ref<Topic[]>([])
  
  function setTopics(newTopics: Topic[]) {
    topics.value = newTopics
  }

  function setStep(step: TutorStep) {
    currentStep.value = step
  }

  function setChildDetails(details: ChildDetails) {
    childDetails.value = details
  }

  function setSelectedSubject(subject: Subject) {
    selectedSubject.value = subject
  }

  function setSkillAssessment(assessment: SkillAssessment) {
    skillAssessment.value = assessment
  }

  function toggleFocusArea(areaId: string) {
    const area = focusAreas.value.find(a => a.id === areaId)
    if (area) {
      area.selected = !area.selected
    }
  }

  function setSelectedTopic(topic: Topic) {
    selectedTopic.value = topic
  }

  function setCurrentLevel(level: Level | null) {
    currentLevel.value = level
  }

  function setCurrentGame(game: Game | null) {
    currentGame.value = game
  }

  function incrementWrongAnswer(questionIndex: number) {
    wrongAnswers.value[questionIndex] = (wrongAnswers.value[questionIndex] || 0) + 1
  }

  function resetWrongAnswers() {
    wrongAnswers.value = {}
  }

  function getLevelProgress(topicId: string): number {
    return levelProgress.value[topicId] || 1
  }

  function setLevelProgress(topicId: string, level: number) {
    levelProgress.value[topicId] = level
  }

  function setCurrentQuiz(quiz: any) {
    currentQuiz.value = quiz
  }

  function setQuizResults(results: QuizResult) {
    quizResults.value = results
  }

  function setConversationId(id: string | null) {
    conversationId.value = id
  }

  function reset() {
    currentStep.value = 'child-details'
    childDetails.value = { name: '' }
    selectedSubject.value = null
    skillAssessment.value = { proficiency: null, subject: null }
    focusAreas.value.forEach(area => area.selected = false)
    selectedTopic.value = null
    currentLevel.value = null
    currentGame.value = null
    currentQuiz.value = null
    quizResults.value = null
    conversationId.value = null
    levelProgress.value = {}
    wrongAnswers.value = {}
  }

    return {
    currentStep,
    childDetails,
    selectedSubject,
    skillAssessment,
    focusAreas,
    selectedTopic,
    currentLevel,
    currentGame,
    currentQuiz,
    quizResults,
    conversationId,
    levelProgress,
    wrongAnswers,
    topics,
    getFocusAreasForSubject,
    setStep,
    setChildDetails,
    setSelectedSubject,
    setSkillAssessment,
    toggleFocusArea,
    setSelectedTopic,
    setTopics,
    setCurrentLevel,
    setCurrentGame,
    setCurrentQuiz,
    setQuizResults,
    setConversationId,
    incrementWrongAnswer,
    resetWrongAnswers,
    getLevelProgress,
    setLevelProgress,
    reset
  }
})

